name: 🎨 Code Quality

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main, develop ]
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  BUN_VERSION: latest

jobs:
  # 🎨 Formatting & Linting
  format-and-lint:
    name: 🎨 Format & Lint
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🟡 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🏗️ Build shared package
        run: bun run build:shared

      - name: 🎨 Check Prettier formatting
        run: |
          echo "🎨 Checking code formatting with Prettier..."
          bun run format:check

      - name: 🎨 Run ESLint
        run: |
          cd client && bun run lint

      - name: 🔍 TypeScript strict checks
        run: |
          echo "🔍 Running strict TypeScript checks..."
          
          # Client strict checks
          echo "Checking client TypeScript..."
          cd client
          bunx tsc --noEmit --strict || echo "⚠️ Client has TypeScript issues"
          cd ..
          
          # Server strict checks  
          echo "Checking server TypeScript..."
          cd server
          bunx tsc --noEmit --strict || echo "⚠️ Server has TypeScript issues"
          cd ..
          
          # Shared strict checks
          echo "Checking shared TypeScript..."
          cd shared
          bunx tsc --noEmit --strict || echo "⚠️ Shared has TypeScript issues"

  # 🔧 Auto-fix (only on push to main branches)
  auto-fix:
    name: 🔧 Auto-fix Issues
    runs-on: ubuntu-latest
    needs: format-and-lint
    if: |
      (github.event_name == 'push') &&
      (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') &&
      failure()
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: 🟡 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🔧 Auto-fix ESLint issues
        run: |
          echo "🔧 Auto-fixing ESLint issues..."
          bun run lint:fix || true

      - name: 🎨 Auto-format with Prettier
        run: |
          echo "🎨 Auto-formatting with Prettier..."
          bun run format || true

      - name: 📝 Commit auto-fixes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            
            try {
              // Check if there are changes to commit
              execSync('git add -A');
              const status = execSync('git status --porcelain').toString();
              
              if (status.trim()) {
                // Configure git
                execSync('git config user.name "github-actions[bot]"');
                execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');
                
                // Commit the changes
                execSync('git commit -m "🤖 Auto-fix: Code formatting and linting issues"');
                execSync('git push');
                
                console.log('✅ Auto-fixes committed and pushed');
              } else {
                console.log('ℹ️ No auto-fixes needed');
              }
            } catch (error) {
              console.log('⚠️ Auto-fix commit failed:', error.message);
            }

  # 📊 Code Metrics & Analysis
  code-metrics:
    name: 📊 Code Metrics
    runs-on: ubuntu-latest
    
    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🟡 Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 📊 Generate code metrics
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            function countLines(dir, extensions = ['.ts', '.tsx', '.js', '.jsx']) {
              let totalLines = 0;
              let totalFiles = 0;
              
              function walkDir(currentPath) {
                const items = fs.readdirSync(currentPath);
                
                items.forEach(item => {
                  const itemPath = path.join(currentPath, item);
                  const stat = fs.statSync(itemPath);
                  
                  if (stat.isDirectory() && !['node_modules', 'dist', '.git'].includes(item)) {
                    walkDir(itemPath);
                  } else if (stat.isFile()) {
                    const ext = path.extname(item);
                    if (extensions.includes(ext)) {
                      const content = fs.readFileSync(itemPath, 'utf8');
                      const lines = content.split('\n').length;
                      totalLines += lines;
                      totalFiles += 1;
                    }
                  }
                });
              }
              
              walkDir(dir);
              return { totalLines, totalFiles };
            }
            
            // Analyze different parts of the codebase
            const clientMetrics = countLines('./client/src');
            const serverMetrics = countLines('./server/src');
            const sharedMetrics = countLines('./shared/src');
            
            const report = `
            ## 📊 Code Metrics Report
            
            ### 📁 Codebase Overview
            | Package | Files | Lines | Avg Lines/File |
            |---------|-------|--------|----------------|
            | Client | ${clientMetrics.totalFiles} | ${clientMetrics.totalLines} | ${Math.round(clientMetrics.totalLines / clientMetrics.totalFiles)} |
            | Server | ${serverMetrics.totalFiles} | ${serverMetrics.totalLines} | ${Math.round(serverMetrics.totalLines / serverMetrics.totalFiles)} |
            | Shared | ${sharedMetrics.totalFiles} | ${sharedMetrics.totalLines} | ${Math.round(sharedMetrics.totalLines / sharedMetrics.totalFiles)} |
            
            **Total:** ${clientMetrics.totalFiles + serverMetrics.totalFiles + sharedMetrics.totalFiles} files, ${clientMetrics.totalLines + serverMetrics.totalLines + sharedMetrics.totalLines} lines
            
            ### 🎯 Code Quality Indicators
            - ✅ ESLint configured for client
            - ✅ TypeScript strict mode enabled  
            - ✅ Monorepo structure with proper separation
            - ✅ Shared types and utilities
            
            _Generated automatically by Code Quality workflow_
            `;
            
            console.log(report);
            
            // Save metrics to file for potential artifacts
            fs.writeFileSync('code-metrics.md', report);

      - name: 📊 Upload code metrics
        uses: actions/upload-artifact@v4
        with:
          name: code-metrics
          path: code-metrics.md
          retention-days: 30

  # ✅ Quality Gate
  quality-gate:
    name: ✅ Quality Gate
    runs-on: ubuntu-latest
    needs: [format-and-lint, code-metrics]
    if: always()
    
    steps:
      - name: ✅ Evaluate quality gate
        uses: actions/github-script@v7
        with:
          script: |
            const jobs = ${{ toJson(needs) }};
            
            const criticalJobs = ['format-and-lint'];
            const failedCriticalJobs = criticalJobs.filter(job => 
              jobs[job] && jobs[job].result === 'failure'
            );
            
            if (failedCriticalJobs.length > 0) {
              const message = `❌ Code quality checks failed: ${failedCriticalJobs.join(', ')}`;
              console.log(message);
              console.log('\n🔧 To fix formatting issues locally, run:');
              console.log('  cd client && bun run lint --fix');
              console.log('  cd client && bunx prettier --write "src/**/*.{ts,tsx,js,jsx,css}"');
              core.setFailed(message);
            } else {
              console.log('✅ All code quality checks passed!');
              
              // Log any warnings from non-critical jobs
              Object.entries(jobs).forEach(([name, job]) => {
                if (job.result === 'failure' && !criticalJobs.includes(name)) {
                  console.log(`⚠️ Non-critical job failed: ${name}`);
                }
              });
            }
